default:
  http_metas:
    content-type: text/html

  metas:
    title:        ESQSites123.com &raquo; Bar Association Area
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       noindex, nofollow

  stylesheets:
    - /teAdminThemePlugin/css/admin
    - /teAdminThemePlugin/css/ui/1011-theme/jquery-ui-1.7.custom.css
    - /gswsAdminThemePlugin/css/ui/smoothness/jquery-ui-1.7.2.custom.css
    - blueprint/src/grid
    - admin
    - plugins/link-icons/screen
    - shared
    - customer
    - bars

  javascripts:
    - swfobject/swfobject
    - jquery/jquery-ui

  has_layout:     true
  layout:         layout
