generator:
  class: sfPropelGenerator
  param:
    model_class:           PageGroup
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          page_group
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:
        actions:
          _list: ~
          _save: ~
      edit:
        title:  Edit Entry
      new:
        title:  Add Entry
