<?php


/**
 * Skeleton subclass for performing query and update operations on the 'te_blog_posts_to_categories' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.1-dev on:
 *
 * 05/06/10 00:32:19
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.teBlogPlugin.lib.model
 */
class teBlogPostToCategoryLinkQuery extends BaseteBlogPostToCategoryLinkQuery {

} // teBlogPostToCategoryLinkQuery
