generator:
  class: sfPropelGenerator
  param:
    model_class:           Domain
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          domain
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:
        title:             Edit Domain "%%name%%"
      new:
        title:             Add New Domain