dev:
  mailer:
    param:
      delivery_strategy: none
      transport:
        class: Swift_NullTransport
test:
  mailer:
    param:
      delivery_strategy: none
      transport:
        class: Swift_NullTransport