<?php


/**
 * Skeleton subclass for performing query and update operations on the 'esq_bar_associations' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.1-dev on:
 *
 * 05/06/10 00:32:16
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class BarAssociationQuery extends BaseBarAssociationQuery
{
  public function withNumCustomers()
  {
    $join = new Join(BarAssociationPeer::ID, CustomerPeer::BAR_ASSOCIATION_ID, Criteria::LEFT_JOIN);
    $join -> addCondition(CustomerPeer::STATUS, Customer::STATUS_ACTIVE);
    $join -> addCondition(CustomerPeer::TYPE, Customer::TYPE_REGULAR);
    
    return $this -> addJoinObject($join, 'customers') ->
      withColumn('COUNT(customers.ID)', "num_customers")->
      groupById();
  }

  public function orderByNumCustomers($order = Criteria::ASC)
  {
    return $this -> orderBy('num_customers', $order);
  }

} // BarAssociationQuery
