<?php


/**
 * Skeleton subclass for performing query and update operations on the 'esq_client_messages' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.1-dev on:
 *
 * 05/06/10 00:32:16
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ClientMessageQuery extends BaseClientMessageQuery
{
  /**
   * @param Customer $customer
   * @return ClientMessageQuery
   */
  public function filterByCustomer(Customer $customer)
  {
    return $this -> useWebsiteQuery() -> filterByCustomer($customer) -> endUse();
  }
} // ClientMessageQuery
