<?php


/**
 * Skeleton subclass for performing query and update operations on the 'esq_email_accounts' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.1-dev on:
 *
 * 05/06/10 00:32:15
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class EmailAccountQuery extends BaseEmailAccountQuery
{
  public function filterByActive()
  {
    return $this -> useDomainQuery() ->
        filterByReal() ->
        useWebsiteQuery() ->
          useCustomerQuery() ->
            filterByReal() ->
          endUse() ->
        endUse() ->
      endUse();
  }
} // EmailAccountQuery
