<?php


/**
 * Skeleton subclass for performing query and update operations on the 'esq_website_attributes' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.1-dev on:
 *
 * 05/06/10 00:32:14
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class WebsiteAttributeQuery extends BaseWebsiteAttributeQuery
{
  /**
   *
   * @param bool $credited_only whether to limit the join to customers that used the bar code to sign up
   * @return HostingPlanQuery 
   */
  public function withNumUsed($credited_only = false)
  {
    $query = $this -> useWebsiteQuery('websites')->
        filterByStatus(Website::STATUS_ACTIVE)->
        useCustomerQuery();

    if($credited_only)
    {
      $query -> filterByCreditBarAssociation(true);
    }

    $query -> filterByReal() ->
        endUse() ->
      endUse()->
      withColumn("COUNT(websites.ID)", "num_used")->
      groupById();

    return $this;
  }
} // WebsiteAttributeQuery
