default:
  http_metas:
    content-type: text/html

  metas:
    title:        ESQSites123.com &raquo; Member Area
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       noindex, nofollow

  stylesheets:
    - /teAdminThemePlugin/css/admin
    - /teAdminThemePlugin/css/ui/1011-theme/jquery-ui-1.7.custom.css
    - /teAdminThemePlugin/css/buttons/screen.css
    - blueprint/src/grid
    - admin
    - shared
    - customer
  javascripts:
    - jquery/jquery-ui

  has_layout:     true
  layout:         layout
